# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52dacd687ea2154e1c20f2ea0fa4b01321a74b4364c1193745f1c4a6206196059e5a3b05773395978b4805fd82bd9d5b58e9b2bfcfc7b42fc73ce53895fe70e6

test:
  secret_key_base: ff5d28c09f8f8e711147bd9ac59470e86b481a31316834d4cc4edda9a334cda119f8330d5382cb36947c20af577c863eaeae9dc4466ddad0c8ee53899609c227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
